version: '3.8'

services:
    client:
        container_name: workshop-client
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client:/app
            - /app/node_modules/
        stdin_open: true
        ports:
            - 3000:3000
        depends_on: 
            - db
            - server
    
    server:
        container_name: workshop-server
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/app
        ports:
            - 5001:5001
        environment: 
            MONGODB_DATABASE: workshopdb
            MONGODB_USERNAME: root
            MONGODB_PASSWORD: example
        depends_on: 
            - db
    
    db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: workshopdb